### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [akshay2000/bertrand-russell_the-problems-of-philosophy#1]
- [x] bibliographical_note filename should use a dash, not an underscore; you will have to update content.opf and the ToC as well.
- [x] bibliographical note: Should be backmatter not bodymatter
- [x] Colophon appears to have strange indentation in the source. The colophon is a file with special formatting and its indentation structure should basically match how it looks like in the bare template: https://github.com/standardebooks/tools/blob/master/se/data/templates/colophon.xhtml
- [x] In the colophon, use `<b class="name">` instead of `<span class="name">`. This was a fairly recent update to the template so it may have occurred after you had already started production.
- [x] In the colophon, don't put a comma after the first transcriber, if there are only two.
- [x] Colophon: `Claesz.` requires `<abbr>`.
- [x] Preface: footer must have a block-level child, usually `<p>`.
- [x] Preface: Abbreviated names like the G. E. in G. E. Moore must be wrapped in `<abbr class="name">`. Are there other instances of initials in the book?
- [x] Metadata: Missing `<dc:description>`
- [x] Metadata long description: The book title is *The* Problems of Philosophy
- [x] Table of contents: `se print-toc` makes a lot of changes. Run `se print-toc -i .` and review its corrections.
- [x] Completely missing semantics, and `<i>` is used throughout where `<em>` would be correct. `<em>` means "emphasis" so it is text that is emphasized or meant to be spoken or read in a different tone of voice. Plain italics almost always require semantic inflection, see https://standardebooks.org/contribute/semantics. In particular books should be wrapped in `<i epub:type="se:name.publication.book">`. Don't just replace all `<i>` with `<em>`, you must carefully consider what the italics is meant to *mean*.

**Comment by akshay2000** [comment]
@acabal I have made some changes and ticked them off above. Can you please review them? In the mean time, I will work on the italics.

**Comment by acabal** [comment]
In the colophon, please indent with tabs; and you are opening some `<b>` tags but closing them with `<span>`. You can run the xhtml through a validator to ensure the structure is valid. `se lint` will also complain if the structure is not valid.

Colophon is also missing the publication year of the book.

Metadata description: "Philosophy" is misspelled as "pholosophy"

`se print-toc -i` still makes changes.

**Comment by akshay2000** [comment]
@acabal Chapter 2 has following sentence:

>  “I think, therefore I am,” he said (_Cogito, ergo sum_); and on the basis of this certainty he set to work to build up again the world of knowledge which his doubt had laid in ruins.

What should we do here with the `<i>` tag? "Cogito, ergo sum" is not really an emphasis here.

I have the same issue with the following as well. These are just words from different language. Not necessarily emphasis.

> The distinction involved is roughly that between _savoir_ and _connaître_ in French, or between _wissen_ and _kennen_ in German.

**Comment by acabal** [comment]
That's fine, then you would use `<i xml:lang="la">` for Latin or `<i xml:lang="fr">` for French.

**Comment by akshay2000** [comment]
@acabal Thank you. On the same note, what about following:

> ...general ideas, such as _whiteness_, _diversity_, _brotherhood_, and so on.

These are instances of the idea, not really emphasis.

Also, this block:

```
<p>The above principle is merely one of a certain number of self-evident logical principles. Some at least of these principles must be granted before any argument or proof becomes possible. When some of them have been granted, others can be proved, though these others, so long as they are simple, are just as obvious as the principles taken for granted. For no very good reason, three of these principles have been singled out by tradition under the name of “Laws of Thought.”</p>
<p>They are as follows:</p>
<ol>
	<li>
		<p><i>The law of identity</i>: “Whatever is, is.”</p>
	</li>
	<li>
		<p><i>The law of contradiction</i>: “Nothing can both be and not be.”</p>
	</li>
	<li>
		<p><i>The law of excluded middle</i>: “Everything must either be or not be.”</p>
	</li>
</ol>
```

**Comment by acabal** [comment]
In the first instance you can replace those with double quotes: https://standardebooks.org/contribute/typography#italics-or-quotes

In the 2nd block you can leave it as-is, without semantics.

**Comment by akshay2000** [comment]
@acabal Excellent. I believe I have dealt with emphasis and semantics. I have also fixed the other things mentioned earlier. Can you confirm this?

**Comment by acabal** [comment]
Great work, thanks! I've gone ahead and released the book :)

**Comment by akshay2000** [comment]
@acabal Thanks a lot!

Just curious about the release process. Looks like the repo is copied under standardebooks account. Why don't we just create a fork? That way standardebooks still gets the full control on the repo and release while preserving link to the source repo.

**Comment by acabal** [comment]
It's easier for us just to clone the repo and create it on the SE account. That way we're the "source of truth", not someone else.

**Comment by akshay2000** [comment]
Makes sense. For my next project. we should probably create the repo on SE account, fork it into my account, and merge back with a PR at the release time.
